
[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
working_directory = "/Users/smin"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[window]
padding.x = 0
padding.y = 0
decorations = "Buttonless"
opacity = 0.97
blur = false
startup_mode = "Windowed"
dynamic_padding = true
dynamic_title = true

[selection]
save_to_clipboard = true


[font]
glyph_offset = { x = 0, y = 0 }
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 16.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2


[keyboard]
bindings = [
  { key = "s", mods = "Command", chars = "\u0013" },
  { key = "1", mods = "Control", chars = "\u00021" },
  { key = "2", mods = "Control", chars = "\u00022" },
  { key = "3", mods = "Control", chars = "\u00023" },
  { key = "4", mods = "Control", chars = "\u00024" },
  { key = "5", mods = "Control", chars = "\u00025" },
  { key = "6", mods = "Control", chars = "\u00026" },
  { key = "7", mods = "Control", chars = "\u00027" },
  { key = "8", mods = "Control", chars = "\u00028" },
  { key = "9", mods = "Control", chars = "\u00029" },
  { key = "f", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
  #{ key = "D",  mods = "Command", chars = "\u0002%" },
  # ⌘ + ⇧ + d adds a pane below (splits window horizontally)
  #{ key = "D",  mods = "Command|Shift", chars = "\u0002\"" },
  #{ key = "Down", mods = "Command", chars = "\u0002\u001b[B" },
  # move up a pane
  #{ key = "Up", mods = "Command", chars = "\u0002\u001b[A" },
  # move left a pane
  #{ key = "Left", mods = "Command", chars = "\u0002\u001b[D" },
  # move right a pane
  #{ key = "Right", mods = "Command", chars = "\u0002\u001b[C" },
  # ⌘ + ⇧ + enter maximizes the pane within the alacritty window
  #{ key = "Enter", mods = "Command|Shift", chars = "\u0002z" },
]

#[terminal.shell]
#program = "/opt/homebrew/bin/zellij"

