[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
working_directory = "/Users/smin"

[colors]
transparent_background_colors = true
draw_bold_text_with_bright_colors = false

[window]
padding.x = 0
padding.y = 0
decorations = "Buttonless"
opacity = 0.90
blur = true
startup_mode = "SimpleFullscreen"
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"


[selection]
save_to_clipboard = true

[font]
size = 15.0


[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2


[keyboard]
bindings = [
  { key = "s", mods = "Command", chars = "\u0013" },
  { key = "f", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
]


[terminal.shell]
program = "/bin/zsh"
args = ["-i", "-c", "t; exec zsh"]
