
[env]
TERM = "xterm-256color"

[general]
live_config_reload = true
working_directory = "/Users/smin"

[colors]
#transparent_background_colors = true
draw_bold_text_with_bright_colors = true

[window]
padding.x = 0
padding.y = 0
decorations = "Buttonless"
opacity = 0.97
blur = false
startup_mode = "Windowed"
dynamic_padding = true
dynamic_title = true

[selection]
save_to_clipboard = true


[font]
glyph_offset = { x = 0, y = 0 }
normal.family = "FiraCode Nerd Font"
normal.style = "Regular"
size = 16.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true

[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2


[keyboard]
bindings = [
  { key = "s", mods = "Command", chars = "\u0013" },
  { key = "f", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
]

[terminal.shell]
program = "/opt/homebrew/bin/tmux"

