[env]
TERM = "alacritty"

[general]
live_config_reload = true
working_directory = "~"

[colors]
transparent_background_colors = false
draw_bold_text_with_bright_colors = false

[window]
padding.x = 2
padding.y = 0
decorations = "Buttonless"
opacity = 1.0
blur = false
startup_mode = "SimpleFullscreen"
dynamic_padding = true
dynamic_title = true
option_as_alt = "OnlyLeft"

[font]
size = 18.0
builtin_box_drawing = true

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[mouse]
hide_when_typing = true


[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>" # Better word selections
save_to_clipboard = true

[keyboard]
bindings = [
  # --- tmux core ---
  { key = "s", mods = "Command", chars = "\u0013" },
  { key = "a", mods = "Command", chars = "\u0001" },
  # Copy (Cmd + C)
  { key = "C", mods = "Command", action = "Copy" },

  # Paste (Cmd + V)
  { key = "V", mods = "Command", action = "Paste" },

  # --- Window management ---
  { key = "t", mods = "Command", chars = "\u0001c" }, # Cmd-t → new window
  { key = "[", mods = "Command", chars = "\u0001p" }, # Cmd-[ → prev window
  { key = "]", mods = "Command", chars = "\u0001n" }, # Cmd-] → next window
  { key = "d", mods = "Command", chars = "\u0001&" }, # Cmd-d → close window

  # --- Pane management ---
  { key = ",", mods = "Command", chars = "\u0001;" },
  { key = ".", mods = "Command", chars = "\u0001o" },
  { key = "x", mods = "Command", chars = "\u0001x" },

  # Cmd-Shift-x → instant kill (no confirm)
  { key = "x", mods = "Command|Shift", chars = "\u0001X" },

  { key = "f", mods = "Command|Shift", action = "ToggleSimpleFullscreen" },
]

# Run the function t in .zshrc to open tmux session
[terminal.shell]
program = "/bin/zsh"
args = ["-i", "-c", "t; exec zsh"]
