[general]
live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "transparent"
opacity = 0.95
dynamic_title = true

[font]
normal.family = "FiraCode Nerd Font"
size = 15

# vertical, slightly thickened cursor
[cursor]
style = "Beam"
unfocused_hollow = false
thickness = 0.2

[terminal]
shell = "/bin/zsh"

[keyboard]
bindings = [
  { key = "s", mods = "Command", chars = "\u0013" },
  { key = "Enter", mods = "Command", action = "ToggleFullscreen" },
  # opt + right and left jump between words
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left", mods = "Alt", chars = "\u001BB" },
  # ⌘ + d adds a pane to the right (splits window vertically)
  { key = "D", mods = "Command", chars = "\u0002%" },
  # ⌘ + ⇧ + d adds a pane below (splits window horizontally)
  { key = "D", mods = "Command|Shift", chars = "\u0002\"" },
  # ⌘ + w prompts you to close the pane, "y" to confirm
  { key = "W", mods = "Command", chars = "\u0002x" },
  # ⌘ + arrows are for directional navigation around the panes
  # move down a pane
  { key = "Down", mods = "Command", chars = "\u0002\u001b[B" },
  # move up a pane
  { key = "Up", mods = "Command", chars = "\u0002\u001b[A" },
  # move left a pane
  { key = "Left", mods = "Command", chars = "\u0002\u001b[D" },
  # move right a pane
  { key = "Right", mods = "Command", chars = "\u0002\u001b[C" },
  # ⌘ + ⇧ + enter maximizes the pane within the alacritty window
  { key = "Enter", mods = "Command|Shift", chars = "\u0002z" },
]
