
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
decorations = "transparent"
startup_mode = "Maximized"
opacity = 1.0

[font]
normal.family = "FiraCode Nerd Font"

size = 15

[keyboard]
bindings = [
     { key = "s", mods = "Command", chars = "\u0013" },
]